using QCUniversidad.Api.Shared.Enums;
using QCUniversidad.WebClient.Models.Teachers;

namespace QCUniversidad.WebClient.Models.LoadItem;

public class LoadViewItemModel
{
    public Guid? LoadId { get; set; }
    public LoadViewItemType Type { get; set; }
    public bool Autogenerated { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public LoadViewItemStatus Status { get; set; }
    public double Value { get; set; } = 0;
    public bool AllowRecalculation { get; set; }
    public NonTeachingLoadType? NonTeachingLoadType { get; set; }
    public Guid TeacherId { get; set; }
    public TeacherModel? Teacher { get; set; }
}