using QCUniversidad.Api.Shared.Dtos.Period;
using QCUniversidad.Api.Shared.Dtos.Teacher;
using QCUniversidad.Api.Shared.Enums;

namespace QCUniversidad.Api.Shared.Dtos.LoadItem;

public record LoadViewItemDto
{
    public Guid? LoadId { get; set; }
    public LoadViewItemType Type { get; set; }
    public bool Autogenerated { get; set; }
    public string? Name { get; set; }
    public string? Description { get; set; }
    public LoadViewItemStatus Status { get; set; } = LoadViewItemStatus.NotSetted;
    public double Value { get; set; } = 0;
    public bool AllowRecalculation { get; set; }
    public NonTeachingLoadType? NonTeachingLoadType { get; set; }
    public Guid TeacherId { get; set; }
    public SimpleTeacherDto? Teacher { get; set; }
    public Guid? PeriodId { get; set; }
    public SimplePeriodDto? Period { get; set; }
}